### ACT-America configuration


###  INPUT/OUTPUT PATHS

# Relative or absolute path to read directory for ICARTT file(s).
DIR_ICARTT: /data/actamerica/ACTAMERICA_Merge/data/ict/

# Relative or absolute path to write directory for netCDF file(s).
PATH_OUTPUT: .dev/outputs/netcdf/

# Relative or absolute path to the variable translation table.
CSV_VARIABLES: resources/actamerica/translation_table.csv

###  RESOURCE FILES

# Repository path to directory for ORNL DAAC reference configurations.
RESOURCES_PATH: resources/

##  EVS PROJECTS

# Repository path to CARVE configuration resources directory.
carve_RESOURCES_PATH: resources/carve/

# Repository path to ACT-America configuration resources directory.
actamerica_RESOURCES_PATH: resources/actamerica/

# Repository path to ATom configuration resources directory.
atom_RESOURCES_PATH: resources/atom/

### OPTIONS

JOIN_MULTILEG: true
